os:
  - linux
  - osx
language: python
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install intltool; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install intltool; fi
  - python ./setup.py -v install
